.\" Manpage for thinklucent.
.\" Contact Mohammed Ismail Ansari <team.terminal@gmail.com> to correct errors or typos.
.TH thinklucent 1 "11/14/2022" "0.1.0"
.SH NAME
thinklucent \- A simple implementation for automatic keyboard backlight in Linux for ThinkPad (and beyond)
.SH SYNOPSIS
.B thinklucent
.SH DESCRIPTION
.B thinklucent
keeps a watch for keyboard and cursor inputs to activate keyboard backlight.
.SH BUGS
No known bugs.
.SH AUTHOR
Mohammed Ismail Ansari (team.terminal@gmail.com)
